spring.application.name=arsw
server.port=8080
spring.mvc.cors.allowed-origins=*
spring.mvc.cors.allowed-methods=*

# Configuración básica para Azure Redis (con SSL)
spring.data.redis.host=bombermanCache.redis.cache.windows.net
spring.data.redis.port=6380
spring.data.redis.password=Mn5XVKNOBncGIYRpPpWldQ1vEEdDmxq2GAzCaH2I7zU=
spring.data.redis.ssl.enabled=true

# Configuración avanzada
spring.data.redis.lettuce.pool.enabled=true
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.timeout=5000ms




